logLevel: "debug"

db:
    username: "postgres"
    password: "1234"
    host: "localhost"
    port: "5432"
    dbname: "postgres"
    sslmode: "disable"

service:
    batchSize: 10

enrichmentClient:
    ageUrl: "https://api.agify.io/?name=Dmitriy"
    genderUrl: "https://api.genderize.io/?name=Dmitriy"
    nationalityUrl: "https://api.nationalize.io/?name=Dmitriy"

apiserver:
    bindAddress: ":3333"